services:
  mysql_db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iot_city_db
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: iot_phpmyadmin
    restart: always
    links:
      - mysql_db
    depends_on:
      - mysql_db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: rootpassword

  iot_fakers:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: iot_fakers
    restart: unless-stopped
    depends_on:
      - mysql_db
      - orion
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
      MYSQL_DB: iot_city_db
    volumes:
      - ./simulation:/app/simulation
      - ./backend:/app/backend
      - ./db_init:/app/db_init
    command: ["bash", "docker/start_fakers.sh"]

  iot_apis:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: iot_apis
    restart: unless-stopped
    depends_on:
      - mysql_db
      - orion
    ports:
      - "8000:8000" # Map API (possible problem because of merge)
      - "8001:8001" # Orion Bridge
      - "8002:8002" # Auth API
      - "8010:8010" # Frontend Map API (possible problem because of merge)
      - "9090:9090" # LLM API
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
      MYSQL_DB: iot_city_db
      ORION_CALLBACK_URL: http://iot-apis:8001
      ORION_URL: http://orion:1026
    networks:
      default:
        aliases:
          - iot-apis
    volumes:
      - ./backend:/app/backend
      - ./simulation:/app/simulation
      - ./db_init:/app/db_init
    command: ["bash", "docker/start_apis.sh"]

  iot_frontends:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: iot_frontends
    restart: unless-stopped
    ports:
      - "5000:5000" # City Dashboard
      - "5173:5173" # Driver PWA
    volumes:
      - ./city_dashboard:/app/city_dashboard
    command: ["bash", "docker/start_frontends.sh"]

  mongo:
    image: mongo:4.4
    container_name: iot_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    command: --nojournal

  orion:
    image: fiware/orion:3.10.1
    container_name: iot_orion
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel DEBUG
