version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: iot_city_db
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: iot_phpmyadmin
    restart: always
    links:
      - mysql_db
    depends_on:
      - mysql_db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: rootpassword
